GET /posts HTTP/1.1
Host: localhost:6000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSJ9LCJpYXQiOjE1OTAxMzg2NjR9.183vGEPJopQGLhvm22kAIAIaz1PVySGdbTbhgKUSBEk
###

POST /posts/login HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "name": "john",
    "email": "john@gmail.com"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSJ9LCJpYXQiOjE1OTAxMzg2NjR9.183vGEPJopQGLhvm22kAIAIaz1PVySGdbTbhgKUSBEk