GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "test1",
    "password": "test"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "name": "test1",
    "password": "testaa"
}